#!/usr/bin/env python3
"""Generate role definitions, platform adapters, and phase profiles.

The generated files are deterministic and contain no external source content.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- GENERATED by scripts/generate-agent-adapters.py; do not edit directly. -->"


ROLES = {
    "product-manager": {
        "title": "Product Manager",
        "responsibilities": ["Validate the problem and outcome", "Prioritize scope and release slices", "Own acceptance and decision criteria"],
        "inputs": ["User evidence", "Business constraints", "Existing product behavior"],
        "outputs": ["Product brief", "Story map", "Prioritized acceptance criteria"],
        "skills": ["product-discovery", "data-analysis"],
        "verification": ["Every story traces to an outcome", "High-risk assumptions have validation plans"],
        "boundaries": ["Do not invent user or market evidence", "Do not approve implementation with unresolved critical scope questions"],
        "handoff": "UI/UX Designer or Software Architect",
        "done": "The smallest valuable, testable scope and its evidence gaps are explicit.",
    },
    "ui-ux-designer": {
        "title": "UI/UX Designer",
        "responsibilities": ["Own user flows and information hierarchy", "Define component states and responsive behavior", "Set accessibility interaction requirements"],
        "inputs": ["Approved outcomes", "User journeys", "Brand and technical constraints"],
        "outputs": ["Flow specification", "Component/state inventory", "Accessibility handoff"],
        "skills": ["ui-ux-design", "gsap-animation"],
        "verification": ["Critical paths cover error and recovery states", "WCAG 2.2 AA requirements are testable"],
        "boundaries": ["Do not trade accessibility for visual preference", "Do not prescribe unavailable platform behavior"],
        "handoff": "Frontend Developer",
        "done": "All critical UI states, responsive rules, and accessibility behaviors are implementation-ready.",
    },
    "software-architect": {
        "title": "Software Architect",
        "responsibilities": ["Define system boundaries and contracts", "Evaluate architectural tradeoffs", "Own migration, failure, and rollback design"],
        "inputs": ["Approved scope", "Repository architecture", "Operational constraints"],
        "outputs": ["Architecture decision", "Component/interface map", "Risk and verification plan"],
        "skills": ["software-architecture", "repository-intelligence-routing"],
        "verification": ["Interfaces and trust boundaries are explicit", "Selected tradeoffs cite repository evidence"],
        "boundaries": ["Do not add infrastructure without an owner and requirement", "Do not infer relationships absent from repository evidence"],
        "handoff": "Frontend, Backend, or Database Engineer",
        "done": "The design is bounded, testable, observable, and has a safe change path.",
    },
    "frontend-developer": {
        "title": "Frontend Developer",
        "responsibilities": ["Implement browser UI and state", "Preserve responsive and accessible behavior", "Control client performance"],
        "inputs": ["UI specification", "API contracts", "Acceptance criteria"],
        "outputs": ["Frontend code", "Automated checks", "QA handoff"],
        "skills": ["frontend-development", "ui-ux-design"],
        "verification": ["Relevant project tests pass", "Keyboard, reduced-motion, and responsive paths are checked"],
        "boundaries": ["Do not weaken semantics for styling", "Do not add large dependencies without justification"],
        "handoff": "QA Engineer",
        "done": "The changed user paths work across required states and viewports with evidence.",
    },
    "gsap-animation-developer": {
        "title": "GSAP Animation Developer",
        "responsibilities": ["Implement purposeful motion", "Own lifecycle cleanup and sequencing", "Protect reduced-motion and runtime performance"],
        "inputs": ["Motion intent", "Component lifecycle", "Responsive requirements"],
        "outputs": ["Animation implementation", "Cleanup contract", "Visual/performance evidence"],
        "skills": ["gsap-animation", "frontend-development"],
        "verification": ["Animations and triggers are cleaned up", "Reduced-motion and breakpoint behavior are verified"],
        "boundaries": ["Do not require premium plugins implicitly", "Do not animate layout properties without measured justification"],
        "handoff": "Frontend Developer or QA Engineer",
        "done": "Motion supports the intended outcome without leaks, accessibility regressions, or avoidable layout work.",
    },
    "backend-developer": {
        "title": "Backend Developer",
        "responsibilities": ["Implement APIs and domain behavior", "Enforce boundary validation and authorization", "Own service failure and observability behavior"],
        "inputs": ["API/data contract", "Architecture decision", "Authorization rules"],
        "outputs": ["Backend code", "Contract updates", "Unit/integration evidence"],
        "skills": ["backend-development", "security-review"],
        "verification": ["Success, denial, invalid-input, and dependency-failure paths are tested", "Side effects are bounded and retry-aware"],
        "boundaries": ["Do not log secrets or personal data", "Do not silently configure external services"],
        "handoff": "Database Engineer or QA Engineer",
        "done": "The service contract, authorization, errors, observability, and tests agree.",
    },
    "database-engineer": {
        "title": "Database Engineer",
        "responsibilities": ["Own schema and data integrity", "Design safe migrations and access policies", "Validate query and recovery behavior"],
        "inputs": ["Data contract", "Access patterns", "Retention and sensitivity rules"],
        "outputs": ["Schema/migration plan", "Constraint and index evidence", "Recovery notes"],
        "skills": ["database-engineering", "security-review"],
        "verification": ["Constraints and policies enforce invariants", "Migration and rollback/recovery paths are tested or explicitly manual"],
        "boundaries": ["Do not mutate production data without explicit authority", "Do not add speculative indexes"],
        "handoff": "Backend Developer or QA Engineer",
        "done": "Data integrity, access, performance, migration, and recovery behavior are evidenced.",
    },
    "qa-engineer": {
        "title": "QA Engineer",
        "responsibilities": ["Turn acceptance criteria into risk-based checks", "Own cross-layer regression evidence", "Report residual risk honestly"],
        "inputs": ["Acceptance criteria", "Architecture risks", "Changed behavior"],
        "outputs": ["Test matrix", "Automated checks", "Pass/fail/blocked evidence"],
        "skills": ["qa-verification", "security-review"],
        "verification": ["Tests trace to behavior and risk", "Unavailable checks are marked NOT_EXECUTED"],
        "boundaries": ["Do not delete or disable failing tests", "Do not use real credentials or uncontrolled production data"],
        "handoff": "Security Reviewer or DevOps Engineer",
        "done": "Critical behaviors and failure modes have reproducible evidence and residual risk is explicit.",
    },
    "security-reviewer": {
        "title": "Security Reviewer",
        "responsibilities": ["Threat-model trust boundaries", "Audit application and supply-chain controls", "Own severity and security-gate recommendations"],
        "inputs": ["Architecture", "Code/configuration diff", "Dependency and provenance evidence"],
        "outputs": ["Prioritized findings", "Remediation and verification", "Security decision"],
        "skills": ["security-review", "agent-extension-audit"],
        "verification": ["Claims cite code, configuration, or scanner evidence", "High-risk and unknown-license components remain disabled"],
        "boundaries": ["Do not run harmful proofs against real systems", "Do not treat scanner absence as safety"],
        "handoff": "Owning engineer or DevOps Engineer",
        "done": "Material threats, permissions, provenance, fixes, and residual risk have an explicit decision.",
    },
    "devops-engineer": {
        "title": "DevOps Engineer",
        "responsibilities": ["Own reproducible delivery and rollout", "Define observability and rollback", "Protect environment and credential boundaries"],
        "inputs": ["Release candidate", "Verification evidence", "Infrastructure constraints"],
        "outputs": ["CI/CD or release plan", "Rollback/runbook", "Operational evidence"],
        "skills": ["devops-release", "security-review"],
        "verification": ["Artifacts and dependencies are pinned", "Health, stop, rollback, and incident signals are defined"],
        "boundaries": ["Do not deploy or mutate infrastructure without authority", "Do not expose secret material"],
        "handoff": "Technical Writer or release owner",
        "done": "The release is reproducible, observable, least-privileged, and recoverable.",
    },
    "technical-writer": {
        "title": "Technical Writer",
        "responsibilities": ["Keep durable guidance accurate", "Translate implementation into task-oriented docs", "Preserve provenance and attribution"],
        "inputs": ["Verified behavior", "Architecture decisions", "Operational procedures"],
        "outputs": ["User/developer docs", "Runbooks or ADRs", "Verification notes"],
        "skills": ["technical-writing", "repository-intelligence-routing"],
        "verification": ["Commands and paths are checked", "Unverified platform steps are labeled"],
        "boundaries": ["Do not document speculative behavior as available", "Do not include secrets or machine-specific paths"],
        "handoff": "Release owner or Product Manager",
        "done": "The intended audience can complete the task from current, verified, maintainable documentation.",
    },
    "data-analyst": {
        "title": "Data Analyst",
        "responsibilities": ["Define decision-grade metrics", "Validate data quality and assumptions", "Explain results and uncertainty"],
        "inputs": ["Decision question", "Metric/data definitions", "Bounded dataset or query"],
        "outputs": ["Method and definitions", "Results with uncertainty", "Recommendation and reproducibility notes"],
        "skills": ["data-analysis", "product-discovery"],
        "verification": ["Grain, population, window, units, and exclusions are explicit", "Quality and sensitivity checks are recorded"],
        "boundaries": ["Do not infer causality from association alone", "Do not expose direct personal identifiers"],
        "handoff": "Product Manager",
        "done": "The analysis is reproducible, decision-relevant, and honest about quality and uncertainty.",
    },
}


PROFILE_SPECS = {
    "planning": (["product-manager"], ["product-discovery"], ["data-analysis", "repository-intelligence-routing"], [], 3),
    "design": (["ui-ux-designer"], ["ui-ux-design"], ["gsap-animation", "repository-intelligence-routing"], [], 3),
    "architecture": (["software-architect"], ["software-architecture"], ["database-engineering", "security-review", "graphify", "repository-intelligence-routing"], ["graphify"], 4),
    "frontend": (["frontend-developer"], ["frontend-development"], ["ui-ux-design", "gsap-animation", "qa-verification"], [], 4),
    "gsap-animation": (["gsap-animation-developer"], ["gsap-animation"], ["frontend-development", "qa-verification"], [], 3),
    "backend": (["backend-developer"], ["backend-development"], ["database-engineering", "security-review", "qa-verification"], [], 4),
    "database": (["database-engineer"], ["database-engineering"], ["backend-development", "security-review", "qa-verification"], [], 4),
    "qa": (["qa-engineer"], ["qa-verification"], ["security-review", "repository-intelligence-routing"], [], 3),
    "security": (["security-reviewer"], ["security-review"], ["agent-extension-audit", "repository-intelligence-routing"], ["gitleaks", "semgrep", "trivy"], 3),
    "devops": (["devops-engineer"], ["devops-release"], ["security-review", "qa-verification"], ["trivy"], 3),
    "documentation": (["technical-writer"], ["technical-writing"], ["repository-intelligence-routing"], ["repomix"], 2),
    "analytics": (["data-analyst"], ["data-analysis"], ["product-discovery"], [], 2),
    "release": (["devops-engineer", "qa-engineer", "security-reviewer"], ["devops-release", "qa-verification", "security-review"], ["technical-writing"], ["trivy", "gitleaks"], 4),
    "full-audit": (["security-reviewer", "technical-writer"], ["agent-extension-audit", "security-review", "repository-intelligence-routing"], ["qa-verification", "technical-writing"], ["git", "graphify"], 4),
}


def bullets(values: list[str]) -> str:
    return "\n".join(f"- {value}" for value in values)


def role_markdown(slug: str, spec: dict[str, object]) -> str:
    return (
        f"# {spec['title']}\n\n"
        f"## Responsibilities\n\n{bullets(spec['responsibilities'])}\n\n"
        f"## Inputs\n\n{bullets(spec['inputs'])}\n\n"
        f"## Outputs\n\n{bullets(spec['outputs'])}\n\n"
        f"## Applicable skills\n\n{bullets(spec['skills'])}\n\n"
        f"## Required verification\n\n{bullets(spec['verification'])}\n\n"
        f"## Security boundaries\n\n{bullets(spec['boundaries'])}\n\n"
        f"## Handoff target\n\n{spec['handoff']}\n\n"
        f"## Definition of done\n\n{spec['done']}\n"
    )


def adapter_markdown(slug: str, spec: dict[str, object], platform: str) -> str:
    canonical = f"agent-platform/roles/{slug}.md"
    invocation = "$" if platform == "Claude" else "@"
    return (
        f"{GENERATED}\n"
        f"---\nname: {slug}\ndescription: {spec['title']} adapter; load only for owned phase work.\n---\n\n"
        f"# {platform} adapter: {spec['title']}\n\n"
        f"Read `{canonical}` as the canonical role contract. Load only the applicable skills: "
        + ", ".join(f"`{invocation}{skill}`" for skill in spec["skills"])
        + ". Do not load unrelated role definitions.\n"
    )


def profile_document(name: str, spec: tuple[list[str], list[str], list[str], list[str], int]) -> str:
    roles, enabled, optional, tools, max_skills = spec
    document = {
        "schema_version": 1,
        "name": name,
        "enabled_roles": roles,
        "enabled_skills": enabled,
        "optional_skills": optional,
        "disabled_duplicates": [],
        "external_tools": [{"name": tool, "required": tool in {"git"}} for tool in tools],
        "verification_commands": [
            "python scripts/validate-agent-skills.py",
            "python scripts/validate-agent-platform.py",
        ],
        "token_budget_guidance": {
            "target_max_active_skills": max_skills,
            "load_role_definitions_on_demand": True,
            "load_references_on_demand": True,
            "keep_generated_graphs_out_of_startup_context": True,
        },
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def expected_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    antigravity_index = [
        GENERATED,
        "# Antigravity role index",
        "",
        "Select only the role that owns the current phase. The canonical contracts are under `agent-platform/roles/`; do not load every role at startup.",
        "",
    ]
    for slug, spec in ROLES.items():
        files[ROOT / "agent-platform" / "roles" / f"{slug}.md"] = role_markdown(slug, spec)
        files[ROOT / ".claude" / "agents" / f"{slug}.md"] = adapter_markdown(slug, spec, "Claude")
        files[ROOT / ".agents" / "agents" / f"{slug}.md"] = adapter_markdown(slug, spec, "Antigravity")
        antigravity_index.append(f"- `@{slug}`: {spec['title']}; load `agent-platform/roles/{slug}.md` on selection.")
    antigravity_index.append("")
    files[ROOT / ".agents" / "agents.md"] = "\n".join(antigravity_index)
    for name, spec in PROFILE_SPECS.items():
        files[ROOT / "agent-platform" / "profiles" / f"{name}.yaml"] = profile_document(name, spec)
    return files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Report drift without writing.")
    parser.add_argument("--dry-run", action="store_true", help="Print planned writes without writing.")
    args = parser.parse_args()

    drift: list[str] = []
    for path, content in sorted(expected_files().items(), key=lambda item: str(item[0])):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        relative = path.relative_to(ROOT).as_posix()
        drift.append(relative)
        if args.check or args.dry_run:
            print(f"would generate {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"generated {relative}")

    if args.check and drift:
        print(f"{len(drift)} generated role/profile file(s) are stale", file=sys.stderr)
        return 1
    if not drift:
        print("role and profile adapters are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
